name: master build image

on:
  push:
    branches: [ master ]

jobs:

  build_image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
